time_units: generations
demes:
- name: A
  epochs:
  - {end_time: 12117, start_size: 18507}
- name: Ghost
  ancestors: [A]
  start_time: 50000
  epochs:
  - {end_time: 0, start_size: 10000}
- name: KS
  ancestors: [A]
  epochs:
  - {end_time: 0, start_size: 86572}
- name: ARHG_RHGn
  ancestors: [A]
  epochs:
  - {end_time: 6726, start_size: 46968}
- name: ARHG
  ancestors: [ARHG_RHGn]
  epochs:
  - {end_time: 892, start_size: 57397} 
- name: RHGn
  ancestors: [ARHG_RHGn]
  epochs:
  - {end_time: 0, start_size: 18022}
- name: wRHG
  ancestors: [ARHG]
  epochs:
  - {end_time: 0, start_size: 9461}
- name: eRHG
  ancestors: [ARHG]
  epochs:
  - {end_time: 0, start_size: 12592}

pulses:
- sources: [KS]
  dest: ARHG_RHGn
  time: 9679
  proportions: [0.5357]
- sources: [ARHG_RHGn]
  dest: KS
  time: 9678
  proportions: [0.3359]
- sources: [KS]
  dest: RHGn
  time: 4490
  proportions: [0.4066]
- sources: [RHGn]
  dest: KS
  time: 4491
  proportions: [0.7032]
- sources: [KS]
  dest: ARHG
  time: 4408
  proportions: [0.5824]
- sources: [ARHG]
  dest: KS
  time: 4407
  proportions: [0.4734]
- sources: [RHGn]
  dest: ARHG
  time: 2756
  proportions: [0.5802]
- sources: [ARHG]
  dest: RHGn
  time: 2757
  proportions: [0.4081]
- sources: [KS]
  dest: RHGn
  time: 1383
  proportions: [0.4827]
- sources: [RHGn]
  dest: KS
  time: 1382
  proportions: [0.3668]
- sources: [wRHG]
  dest: eRHG
  time: 411
  proportions: [0.5034]
- sources: [eRHG]
  dest: wRHG
  time: 410
  proportions: [0.5453]
- sources: [eRHG]
  dest: RHGn
  time: 393
  proportions: [0.6072]
- sources: [RHGn]
  dest: eRHG
  time: 394
  proportions: [0.3305]
- sources: [wRHG]
  dest: RHGn
  time: 302
  proportions: [0.3925]
- sources: [RHGn]
  dest: wRHG
  time: 303
  proportions: [0.6461]
- sources: [Ghost]
  dest: KS
  time: 2758
  proportions: [0.02]
